spring:
  config:
    import: "optional:secrets.yml"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwks_uri: https://www.googleapis.com/oauth2/v3/certs

server:
  port: 8080

  error:
    include-exception: false
    include-binding-errors: always
    include-stacktrace: never
    include-message: always

logging:
  level:
    org:
      springframework: INFO
#      springframework.data.mongodb: DEBUG
#      springframework.security.oauth2: DEBUG
