spring:
  data:
    mongodb:
      uri: XX
      database: XX

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: XX
            client-secret: XX
          github:
            client-id: XX
            client-secret: XX
            scope:
              - read:user
              - user:email
